/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ucsc.groupone.dialogs;

import com.ucsc.groupone.models.Coordinate;
import com.ucsc.groupone.models.PathPlan;
import com.ucsc.groupone.utils.FileChooserOptions;
import com.ucsc.groupone.utils.SystemConstants;
import com.ucsc.groupone.utils.Validator;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hashan
 */
public class PathPlanning extends javax.swing.JDialog {

    private PathPlan pathPlan;
    private DefaultTableModel coordinatesTableModel;

    public PathPlanning(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        longitude = new javax.swing.JTextField();
        latitude = new javax.swing.JTextField();
        addMarkerButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        messageBox1 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        allMarkersTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        altitude = new javax.swing.JTextField();
        planName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        uavSpeed = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        savePath = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        messageBox2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Add Markers");

        jLabel2.setText("Longitude");

        jLabel3.setText("Latitude");

        addMarkerButton.setText("Add Coordinate");
        addMarkerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMarkerButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("All Markers");

        messageBox1.setForeground(new java.awt.Color(255, 0, 0));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        allMarkersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Latitude", "Longitude", "Altitude"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        allMarkersTable.setColumnSelectionAllowed(true);
        allMarkersTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(allMarkersTable);
        allMarkersTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (allMarkersTable.getColumnModel().getColumnCount() > 0) {
            allMarkersTable.getColumnModel().getColumn(0).setResizable(false);
            allMarkersTable.getColumnModel().getColumn(1).setResizable(false);
            allMarkersTable.getColumnModel().getColumn(2).setResizable(false);
            allMarkersTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel5.setText("Altitude");

        jLabel6.setText("UAV Speed");

        jLabel7.setText("Name");

        uavSpeed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uavSpeedKeyPressed(evt);
            }
        });

        jLabel8.setText("Save Path");

        savePath.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N

        browseButton.setText("...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        messageBox2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(savePath)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(planName, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uavSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(latitude, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(longitude, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addMarkerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(altitude)))
                            .addComponent(messageBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(messageBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(longitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(latitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(altitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addMarkerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(uavSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(planName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(savePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(browseButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMarkerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMarkerButtonActionPerformed
        try {
            double longitudeVal = Double.parseDouble(longitude.getText());
            double latitudeVal = Double.parseDouble(latitude.getText());
            double altitudeVal = Double.parseDouble(altitude.getText());
            int coordinateId = findNewCoordinateId();
            this.pathPlan.addCoordinate(new Coordinate(coordinateId, latitudeVal, longitudeVal, altitudeVal));
            updateCoordinateDisplayArea();
            longitude.setText("");
            latitude.setText("");
            altitude.setText("");
        } catch (Exception ex) {
            ex.printStackTrace();
            messageBox1.setText(SystemConstants.INVALID_COORDINATES);
        }
    }//GEN-LAST:event_addMarkerButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            String planName = this.planName.getText().trim();
            double uavSpeed = Double.parseDouble(this.uavSpeed.getText().trim());
            String fileSavePath = this.savePath.getText().trim();

            if ("".equals(planName) || "".equals(fileSavePath)) {
                this.messageBox2.setText(SystemConstants.REQUIRED);
            } else {
                this.pathPlan.setFilePath(fileSavePath);
                this.pathPlan.setSpeed(uavSpeed);
                this.pathPlan.setName(planName);
                pathPlan.setIcon(new ImageIcon(SystemConstants.PATH_TO_MODEL_ICON));
                this.dispose();
            }

        } catch (Exception ex) {
            this.messageBox2.setText(SystemConstants.INVALID_UAV_SPEED);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        FileChooserOptions.chooseFilePath("Choose Path Folder To Save",
                JFileChooser.DIRECTORIES_ONLY,
                savePath,
                null);
    }//GEN-LAST:event_browseButtonActionPerformed

    private void uavSpeedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uavSpeedKeyPressed
        Validator.validateDoubleInput(evt, uavSpeed, messageBox2);
    }//GEN-LAST:event_uavSpeedKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PathPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PathPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PathPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PathPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PathPlanning dialog = new PathPlanning(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public PathPlan showDialog(PathPlan pathPlan) {
        if (pathPlan == null) {
            this.pathPlan = new PathPlan();
            this.pathPlan.setCoordinateList(new ArrayList<>());
        } else {
            this.pathPlan = pathPlan;
            updateCoordinateDisplayArea();
        }
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        return this.pathPlan;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMarkerButton;
    private javax.swing.JTable allMarkersTable;
    private javax.swing.JTextField altitude;
    private javax.swing.JButton browseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField latitude;
    private javax.swing.JTextField longitude;
    private javax.swing.JLabel messageBox1;
    private javax.swing.JLabel messageBox2;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField planName;
    private javax.swing.JTextField savePath;
    private javax.swing.JTextField uavSpeed;
    // End of variables declaration//GEN-END:variables

    private void initFields() {
        longitude.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                Validator.validateDoubleInput(evt, longitude, messageBox1);
            }
        });

        latitude.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                Validator.validateDoubleInput(evt, latitude, messageBox1);
            }
        });
    }

    private int findNewCoordinateId() {
        return this.pathPlan.getCoordinateList().size() + 1;
    }

    private void updateCoordinateDisplayArea() {
        coordinatesTableModel = (DefaultTableModel) allMarkersTable.getModel();
        coordinatesTableModel.setNumRows(0);
        for (Coordinate coordinate : this.pathPlan.getCoordinateList()) {
            coordinatesTableModel.addRow(new Object[]{coordinate.getPointId(),
                coordinate.getLatitude(), coordinate.getLongitude(), coordinate.getAltitude()});
        }
    }
}
