/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ucsc.groupone.frames;

import com.ucsc.groupone.dialogs.CreateProject;
import com.ucsc.groupone.logger.WizardLogger;
import com.ucsc.groupone.mappers.ModelMapper;
import com.ucsc.groupone.models.ClassifierModel;
import com.ucsc.groupone.popup.OpenProject;
import com.ucsc.groupone.utils.Extensions;
import com.ucsc.groupone.utils.SystemConstants;
import com.ucsc.groupone.utils.SystemVariables;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.util.EntityUtils;

/**
 *
 * @author hashan
 */
public class StartFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        createProjectIcon = new javax.swing.JLabel();
        createProjectLabel = new javax.swing.JLabel();
        openProjectIcon = new javax.swing.JLabel();
        openProjectLabel = new javax.swing.JLabel();
        closeProjectLabel = new javax.swing.JLabel();
        closeProjectIcon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome To Tea-Wizard");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        createProjectIcon.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        createProjectIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\Tea-Wizard\\src\\main\\java\\resources\\add.png")); // NOI18N
        createProjectIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        createProjectLabel.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        createProjectLabel.setText("Create New Project");
        createProjectLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createProjectLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createProjectLabelMouseClicked(evt);
            }
        });

        openProjectIcon.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        openProjectIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\Tea-Wizard\\src\\main\\java\\resources\\open-project.png")); // NOI18N
        openProjectIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        openProjectLabel.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        openProjectLabel.setText("Open Project");
        openProjectLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openProjectLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openProjectLabelMouseClicked(evt);
            }
        });

        closeProjectLabel.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        closeProjectLabel.setText("Close");
        closeProjectLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeProjectLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeProjectLabelMouseClicked(evt);
            }
        });

        closeProjectIcon.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        closeProjectIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\Tea-Wizard\\src\\main\\java\\resources\\close.png")); // NOI18N
        closeProjectIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeProjectIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeProjectIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(closeProjectIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeProjectLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(openProjectIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openProjectLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(createProjectIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createProjectLabel)))
                .addGap(106, 106, 106))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createProjectLabel)
                    .addComponent(createProjectIcon))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(openProjectLabel)
                    .addComponent(openProjectIcon))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeProjectLabel)
                    .addComponent(closeProjectIcon))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel1.setText("TEA-WIZARD");

        jLabel3.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        jLabel3.setText("Version 2020.1.1");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\Tea-Wizard\\src\\main\\java\\resources\\model-workspace-icon.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(113, 113, 113))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createProjectLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createProjectLabelMouseClicked
        openCreateNewProjectWindow();
    }//GEN-LAST:event_createProjectLabelMouseClicked

    private void openProjectLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openProjectLabelMouseClicked
        OpenProject openProject = new OpenProject(this);
        ClassifierModel model = openProject.getModel();
        if (model != null) {
            if (model.getPath() != null) {
                model.setIcon(new ImageIcon(SystemConstants.PATH_TO_MODEL_ICON));
            } else {
                model = null;
            }
            MasterFrame masterFrame = new MasterFrame(model, SystemVariables.projectRootFolder);
            masterFrame.setVisible(true);
            masterFrame.setLocationRelativeTo(null);
            this.dispose();
        }

        WizardLogger.log("Open Project ", Level.INFO, null);
    }//GEN-LAST:event_openProjectLabelMouseClicked

    private void closeProjectLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeProjectLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeProjectLabelMouseClicked

    private void closeProjectIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeProjectIconMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeProjectIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StartFrame startFrame = new StartFrame();
                startFrame.setVisible(true);
                startFrame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeProjectIcon;
    private javax.swing.JLabel closeProjectLabel;
    private javax.swing.JLabel createProjectIcon;
    private javax.swing.JLabel createProjectLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel openProjectIcon;
    private javax.swing.JLabel openProjectLabel;
    // End of variables declaration//GEN-END:variables

    private void openCreateNewProjectWindow() {
        CreateProject newProject = new CreateProject(this, rootPaneCheckingEnabled);
        String projectPath = newProject.showDialog();
        if (projectPath != null) {
            if (projectPath.equals(SystemConstants.RETURN_ERROR)) {
                JOptionPane.showMessageDialog(this, SystemConstants.PROJECT_CREATION_ERROR, SystemConstants.ERROR, JOptionPane.ERROR_MESSAGE);
            } else if (projectPath.equals(SystemConstants.RETURN_SUCCESS)) {
                this.dispose();
                MasterFrame masterFrame = new MasterFrame();
                masterFrame.setVisible(true);
                masterFrame.setLocationRelativeTo(null);
            }
        }
    }

}
